### ISSUE TITLE
Why panic instead of returning error?

### ISSUE THREAD

**Issue by Congyuwang** [Marcono1234/struson#86]
I see that there are a LOT of `panics` in this crate. Why is it so designed? Why not just return some InvalidData std::io::Error or crate defined error?

**Comment by Congyuwang** [comment]
Okay I see that only incorrect API usage can cause panic.

**Comment by Marcono1234** [comment]
`JsonReader` and `JsonWriter` API (and their implementation) is pretty flexible, at the cost of incorrect usage not being detectable at compile time. Therefore, if they are used incorrectly they panic at runtime. But as you mention, _a panic can only happen due to incorrect usage_. For correct usage this cannot happen regardless of what JSON data you process (if a panic does happen, I would consider that bug).

There is also the [Simple API](https://github.com/Marcono1234/struson/tree/v0.5.0?tab=readme-ov-file#simple-api) which implicitly enforces correct usage, and except for a few explicitly documented cases does not panic. However, its API is less flexible.
